apiVersion: v1
kind: Service
metadata:
  name: coatrack-admin
  namespace: coatrack
spec:
  selector:
    app.kubernetes.io/name: coatrack-admin
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
